const apiAccount = [
  {
    name: "Sitlexa",
    league: "Standard",
    classId: 2,
    ascendancyClass: 2,
    class: "Deadeye",
    level: 88,
    experience: 1648890860,
  },
  {
    name: "WeLoveJS",
    league: "Harvest",
    classId: 6,
    ascendancyClass: 1,
    class: "Assassin",
    level: 93,
    experience: 2456740308,
    lastActive: true,
  },
  {
    name: "THE_TRUMPNATOR",
    league: "Standard",
    classId: 1,
    ascendancyClass: 2,
    class: "Berserker",
    level: 90,
    experience: 1935918832,
  },
  {
    name: "KidsLikeViolence",
    league: "Standard",
    classId: 2,
    ascendancyClass: 2,
    class: "Deadeye",
    level: 94,
    experience: 2658379264,
  },
  {
    name: "majK_K",
    league: "Standard",
    classId: 1,
    ascendancyClass: 2,
    class: "Berserker",
    level: 93,
    experience: 2455921256,
  },
  {
    name: "Aegon_Targaryen_",
    league: "Standard",
    classId: 5,
    ascendancyClass: 1,
    class: "Inquisitor",
    level: 97,
    experience: 3364828162,
  },
  {
    name: "FirstTimeDoingRace",
    league: "Standard",
    classId: 5,
    ascendancyClass: 1,
    class: "Inquisitor",
    level: 79,
    experience: 802307764,
  },
  {
    name: "majKmonster",
    league: "Standard",
    classId: 2,
    ascendancyClass: 3,
    class: "Pathfinder",
    level: 90,
    experience: 1934009687,
  },
  {
    name: "TrickUrMind",
    league: "Standard",
    classId: 6,
    ascendancyClass: 2,
    class: "Trickster",
    level: 89,
    experience: 1825280967,
  },
  {
    name: "mmmajK",
    league: "Standard",
    classId: 3,
    ascendancyClass: 1,
    class: "Occultist",
    level: 92,
    experience: 2268549086,
  },
];

export default apiAccount;
